apiVersion: v1
kind: Service
metadata:
  name: redhat-service
spec:
  selector:
    app: redhat
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 80
      targetPort: 9254
  type: NodePort